name: "Buildkite Agentic Example"
description: "An example of an agentic pipeline that listens for GitHub PR label events and fixes broken builds."
emoji: ":buildkite:"
languages:
  - "TypeScript"

steps:
  - label: ":pipeline:"
    command: "buildkite-agent pipeline upload"
    depends_on: []
